name: CI

on:
  push:
    branches: [ main ]
    tags: [ v*.*.* ]

  pull_request:
    branches: [ "main" ]
    types:
      - synchronize
      - opened
      - reopened

jobs:
  call_ci:
    uses: EffectiveRange/ci-workflows/.github/workflows/python-ci.yaml@latest-python

  push_docker_image:
    if: startsWith(github.ref, 'refs/tags/')
    needs: call_ci
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: debian-package-collector_wheel
          path: ${{ github.workspace }}/dist

      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: effectiverange/debian-package-collector

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
