name: Python release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish-and-release:
    name: Publish and release distributions

    runs-on: ubuntu-latest

    permissions:
      contents: write
      discussions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Package and publish
        uses: EffectiveRange/python-package-github-action@v1
        with:
          debian-dist-type: 'library'
          post-build-command: 'make service TAG=${GITHUB_REF#refs/tags/}'
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: effectiverange/debian-package-collector
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Release
        uses: EffectiveRange/version-release-github-action@v1
